// apps/web-vue/src/components/admin/column-visibility-toggle.vue
<script setup lang="ts">
import { Columns3 } from 'lucide-vue-next';

import Button from '@/components/ui/button.vue';
import {
  DropdownMenu,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu.vue';

const props = defineProps<{
  columns: Array<{ id: string; label: string }>;
  modelValue: string[];
}>();

const emit = defineEmits<{ 'update:modelValue': [value: string[]] }>();

function toggleColumn(columnId: string) {
  emit(
    'update:modelValue',
    props.modelValue.includes(columnId)
      ? props.modelValue.filter((id) => id !== columnId)
      : [...props.modelValue, columnId],
  );
}
</script>

<template>
  <DropdownMenu>
    <DropdownMenuTrigger as-child>
      <Button
        variant="outline"
        class="border-wds-accent/30 bg-wds-background text-wds-text hover:bg-wds-accent/10"
      >
        <Columns3 class="h-4 w-4" />
        Columns
      </Button>
    </DropdownMenuTrigger>
    <DropdownMenuContent
      align="end"
      class="border-wds-accent/30 bg-wds-background text-wds-text w-48"
    >
      <DropdownMenuLabel>Toggle columns</DropdownMenuLabel>
      <DropdownMenuSeparator class="bg-wds-accent/20" />
      <DropdownMenuCheckboxItem
        v-for="column in columns"
        :key="column.id"
        :checked="modelValue.includes(column.id)"
        class="focus:bg-wds-accent/10 focus:text-wds-text"
        @select="toggleColumn(column.id)"
      >
        {{ column.label }}
      </DropdownMenuCheckboxItem>
    </DropdownMenuContent>
  </DropdownMenu>
</template>

// apps/web/src/components/admin/ColumnVisibilityToggle.tsx
'use client';

import { Columns3 } from 'lucide-react';
import { useState } from 'react';

import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';

interface Column {
  id: string;
  label: string;
}

interface ColumnVisibilityToggleProps {
  columns: Column[];
  visibleColumns: string[];
  onVisibilityChange: (visibleColumns: string[]) => void;
}

export function ColumnVisibilityToggle({
  columns,
  visibleColumns,
  onVisibilityChange,
}: ColumnVisibilityToggleProps) {
  const [open, setOpen] = useState(false);

  const toggleColumn = (columnId: string) => {
    if (visibleColumns.includes(columnId)) {
      onVisibilityChange(visibleColumns.filter((id) => id !== columnId));
    } else {
      onVisibilityChange([...visibleColumns, columnId]);
    }
  };

  return (
    <DropdownMenu open={open} onOpenChange={setOpen}>
      <DropdownMenuTrigger asChild>
        <Button
          variant="outline"
          className="border-wds-accent/30 bg-wds-background text-wds-text hover:bg-wds-accent/10"
        >
          <Columns3 className="h-4 w-4" />
          Columns
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent
        align="end"
        className="border-wds-accent/30 bg-wds-background text-wds-text w-48"
      >
        <DropdownMenuLabel>Toggle columns</DropdownMenuLabel>
        <DropdownMenuSeparator className="bg-wds-accent/20" />
        {columns.map((column) => (
          <DropdownMenuCheckboxItem
            key={column.id}
            checked={visibleColumns.includes(column.id)}
            onCheckedChange={() => toggleColumn(column.id)}
            className="focus:bg-wds-accent/10 focus:text-wds-text"
          >
            {column.label}
          </DropdownMenuCheckboxItem>
        ))}
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
