// apps/web-vue/src/components/shop/product-page-content.vue
<script setup lang="ts">
import { useRouter } from 'vue-router';
import { computed, ref, watch } from 'vue';

import { useAuth } from '@/composables/use-auth';
import { useAddToCart } from '@/lib/api/hooks/use-cart';
import { useSuspenseProduct } from '@/lib/api/hooks/use-products';
import { toast } from '@/lib/toast';
import { getBackendSlug } from '@/lib/product-slug-mapping';
import { getProductStaticContent } from '@/lib/product-static-content';

import ProductActions from './product-actions.vue';
import ProductAdditionalInfo from './product-additional-info.vue';
import ProductFeatures from './product-features.vue';
import ProductImageGallery from './product-image-gallery.vue';
import ProductInfo from './product-info.vue';
import ProductQuantitySelector from './product-quantity-selector.vue';
import ProductReviews from './product-reviews.vue';
import ProductSizeGuide from './product-size-guide.vue';
import ProductSizeSelector from './product-size-selector.vue';
import ReviewForm from './review-form.vue';

import type { ProductSize } from '@/types/product';

const props = defineProps<{
  productSlug: 'ao-thun' | 'pad-chuot' | 'day-deo' | 'moc-khoa';
  productName: string;
}>();

const selectedSize = ref<ProductSize>('M');
const quantity = ref(1);

const router = useRouter();
const BACKEND_SLUG = getBackendSlug(props.productSlug);
const { user, isAuthenticated } = useAuth();

const { data: product, isLoading } = useSuspenseProduct(BACKEND_SLUG);

const staticContent = getProductStaticContent(BACKEND_SLUG);

const addToCartMutation = useAddToCart();

const stockBySize = computed(() =>
  product.value?.sizeStocks?.reduce(
    (acc, ss) => {
      acc[ss.size] = ss.stock;
      return acc;
    },
    {} as Record<ProductSize, number>,
  ),
);
const selectedSizeStock = computed(
  () => stockBySize.value?.[selectedSize.value] ?? product.value?.stock ?? 0,
);

// Clamp quantity when the selected size's stock is lower than current quantity
// (React does this in render phase; a watcher is the Vue equivalent).
watch(selectedSizeStock, (stock) => {
  if (product.value?.hasSizes && quantity.value > stock) {
    quantity.value = stock > 0 ? stock : 1;
  }
});

const handleAddToCart = () => {
  if (!product.value) return;

  // For products with sizes (ao-thun)
  if (product.value.hasSizes) {
    // Validation: ensure size is selected
    if (!selectedSize.value) {
      toast.error('Vui lòng chọn size');
      return;
    }

    // Validation: quantity must be valid
    if (quantity.value <= 0 || quantity.value > selectedSizeStock.value) {
      toast.error('Số lượng không hợp lệ');
      return;
    }

    addToCartMutation.mutate({
      productId: product.value.id,
      size: selectedSize.value,
      quantity: quantity.value,
    });
  } else {
    // Validation: quantity must be valid
    if (quantity.value <= 0 || quantity.value > product.value.stock) {
      toast.error('Số lượng không hợp lệ');
      return;
    }

    addToCartMutation.mutate({
      productId: product.value.id,
      quantity: quantity.value,
    });
  }
};

const handleBuyNow = () => {
  if (!product.value || !isAuthenticated.value) {
    toast.error('Vui lòng đăng nhập để mua hàng');
    router.push('/auth/login');
    return;
  }

  // Check stock
  const availableStock = product.value.hasSizes
    ? product.value.sizeStocks?.find((ss) => ss.size === selectedSize.value)?.stock || 0
    : product.value.stock || 0;

  if (quantity.value > availableStock) {
    toast.error(`Số lượng vượt quá tồn kho. Tồn kho hiện tại: ${availableStock}`);
    return;
  }

  router.push(
    `/checkout?buyNow=true&productId=${product.value.id}&productSlug=${BACKEND_SLUG}&size=${selectedSize.value}&quantity=${quantity.value}`,
  );
};

const increaseQuantity = () => {
  if (!product.value) return;
  quantity.value = Math.min(
    quantity.value + 1,
    product.value.hasSizes ? (selectedSizeStock.value ?? 10) : (product.value.stock ?? 10),
  );
};

const decreaseQuantity = () => {
  quantity.value = Math.max(quantity.value - 1, 1);
};

// Map backend ProductDto to component props
const price = computed(() => ({
  current: product.value?.priceCurrent ?? 0,
  original: product.value?.priceOriginal ?? undefined,
  discount: product.value?.priceDiscount ?? undefined,
}));

const rating = computed(() => ({
  value: product.value?.ratingValue ?? 0,
  count: product.value?.ratingCount ?? 0,
}));

const sizes = computed(() => product.value?.sizeStocks?.map((ss) => ss.size) || []);
</script>

<template>
  <!-- Mirrors apps/web shop/(shop)/layout.tsx: ambient glow + page container. -->
  <div
    class="bg-wds-background text-wds-text selection:bg-wds-accent/30 selection:text-wds-text min-h-screen"
  >
    <!-- Background ambient glow -->
    <div class="fixed inset-0 -z-10 overflow-hidden">
      <div
        class="bg-wds-accent/20 absolute top-[-10%] left-[-10%] h-[40%] w-[40%] rounded-full blur-[120px]"
      />
      <div
        class="absolute right-[-10%] bottom-[-10%] h-[40%] w-[40%] rounded-full bg-purple-500/20 blur-[120px]"
      />
    </div>

    <div class="relative z-10 pt-24 pb-20">
      <div class="mx-auto max-w-7xl px-6">
        <!-- Loading skeleton (apps/web Suspense fallback) -->
        <div v-if="isLoading || !product" class="flex flex-col gap-12">
          <!-- Breadcrumb Skeleton -->
          <div class="h-5 w-48 animate-pulse rounded bg-white/10" />

          <!-- Product Section Skeleton -->
          <div class="grid grid-cols-1 gap-12 lg:grid-cols-2 lg:gap-16">
            <!-- Image Skeleton -->
            <div class="space-y-4">
              <div class="aspect-square w-full animate-pulse rounded-xl bg-white/10" />
              <div class="grid grid-cols-4 gap-4">
                <div
                  v-for="i in 4"
                  :key="i"
                  class="aspect-square animate-pulse rounded-lg bg-white/10"
                />
              </div>
            </div>

            <!-- Info Skeleton -->
            <div class="flex flex-col justify-center space-y-6">
              <div class="h-8 w-3/4 animate-pulse rounded bg-white/10" />
              <div class="h-4 w-1/2 animate-pulse rounded bg-white/10" />
              <div class="h-6 w-1/3 animate-pulse rounded bg-white/10" />
              <div class="h-20 w-full animate-pulse rounded bg-white/10" />
              <div class="h-12 w-32 animate-pulse rounded bg-white/10" />
              <div class="h-12 w-full animate-pulse rounded bg-white/10" />
              <div class="h-12 w-full animate-pulse rounded bg-white/10" />
            </div>
          </div>
        </div>

        <template v-else>
          <!-- Breadcrumb -->
          <nav class="mb-8 flex items-center gap-2 text-sm text-white/60">
            <RouterLink to="/shop" class="hover:text-wds-accent transition-colors">Shop</RouterLink>
            <span>/</span>
            <span class="text-white/90">{{ productName }}</span>
          </nav>

          <!-- Product Section -->
          <div class="grid grid-cols-1 gap-12 lg:grid-cols-2 lg:gap-16">
            <!-- Left: Product Image -->
            <ProductImageGallery
              :images="staticContent.images"
              :badge="product.badge || undefined"
            />

            <!-- Right: Product Info -->
            <div class="flex flex-col justify-center">
              <ProductInfo
                :name="product.name"
                :rating="rating"
                :price="price"
                :description="product.description"
                price-note="Giá đã bao gồm VAT. Miễn phí vận chuyển cho đơn hàng trên 500.000₫"
              />

              <!-- Size Selector -->
              <ProductSizeSelector
                v-if="product.hasSizes && sizes.length > 0"
                :sizes="sizes"
                :selected-size="selectedSize"
                :stock-by-size="stockBySize"
                @size-change="(size: ProductSize) => (selectedSize = size)"
              />

              <!-- Quantity Selector -->
              <ProductQuantitySelector
                :quantity="quantity"
                :stock="product.hasSizes ? selectedSizeStock : product.stock"
                :max="product.hasSizes ? (selectedSizeStock ?? 0) : (product.stock ?? 0)"
                @increase="increaseQuantity"
                @decrease="decreaseQuantity"
              />

              <!-- Add to Cart Button -->
              <ProductActions
                :is-adding-to-cart="addToCartMutation.isPending.value"
                @add-to-cart="handleAddToCart"
                @buy-now="handleBuyNow"
              />

              <!-- Product Features -->
              <ProductFeatures :features="staticContent.features" />
            </div>
          </div>

          <!-- Additional Info Section -->
          <ProductAdditionalInfo :info="staticContent.additionalInfo" />

          <!-- Size Guide Section - Only for products with sizes -->
          <ProductSizeGuide v-if="product.hasSizes" />

          <!-- Reviews Section -->
          <section class="mt-16">
            <h2 class="mb-8 text-3xl font-bold text-white">Đánh giá sản phẩm</h2>

            <!-- Review Form - Only for authenticated users -->
            <div v-if="isAuthenticated" class="mb-8">
              <ReviewForm :product-slug="BACKEND_SLUG" :current-user-id="user?.id" />
            </div>
            <div v-else class="mb-8 rounded-xl border border-white/10 bg-white/5 p-6">
              <p class="text-white/60">Đăng nhập để viết đánh giá về sản phẩm này.</p>
            </div>

            <!-- Reviews List -->
            <ProductReviews
              :product-slug="BACKEND_SLUG"
              :current-user-id="user?.id"
              :current-user-role="user?.role"
            />
          </section>
        </template>
      </div>
    </div>
  </div>
</template>

// apps/web/src/app/shop/(shop)/ProductPageContent.tsx
'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { Suspense, useEffect, useState } from 'react';
import { toast } from 'sonner';

import { ProductActions } from '@/components/shop/ProductActions';
import { ProductAdditionalInfo } from '@/components/shop/ProductAdditionalInfo';
import { ProductFeatures } from '@/components/shop/ProductFeatures';
import { ProductImageGallery } from '@/components/shop/ProductImageGallery';
import { ProductInfo } from '@/components/shop/ProductInfo';
import { ProductQuantitySelector } from '@/components/shop/ProductQuantitySelector';
import { ProductReviews } from '@/components/shop/ProductReviews';
import { ProductSizeGuide } from '@/components/shop/ProductSizeGuide';
import { ProductSizeSelector } from '@/components/shop/ProductSizeSelector';
import { ReviewForm } from '@/components/shop/ReviewForm';
import { useAuth } from '@/hooks/use-auth';
import { useAddToCart } from '@/lib/api/hooks/use-cart';
import { useSuspenseProduct } from '@/lib/api/hooks/use-products';
import { getBackendSlug } from '@/lib/product-slug-mapping';
import { getProductStaticContent } from '@/lib/product-static-content';
import { ProductSize } from '@/types/product';

interface ProductPageContentProps {
  productSlug: 'ao-thun' | 'pad-chuot' | 'day-deo' | 'moc-khoa';
  productName: string;
}

function ProductContentInner({
  productSlug,
  productName,
}: ProductPageContentProps) {
  const [selectedSize, setSelectedSize] = useState<ProductSize>('M');
  const [quantity, setQuantity] = useState(1);

  const router = useRouter();
  const BACKEND_SLUG = getBackendSlug(productSlug);
  const { user, isAuthenticated } = useAuth();

  // Fetch product data using Suspense Query
  const { data: product } = useSuspenseProduct(BACKEND_SLUG);

  // Get static content (images, features, additionalInfo)
  const staticContent = getProductStaticContent(BACKEND_SLUG);

  // Add to cart mutation
  const addToCartMutation = useAddToCart();

  const handleAddToCart = async () => {
    if (!product) return;

    // For products with sizes (ao-thun)
    if (product.hasSizes) {
      // Validation: ensure size is selected
      if (!selectedSize) {
        toast.error('Vui lòng chọn size');
        return;
      }

      // Calculate stock for selected size
      const stockBySize = product.sizeStocks?.reduce(
        (acc, ss) => {
          acc[ss.size] = ss.stock;
          return acc;
        },
        {} as Record<ProductSize, number>
      );
      const selectedSizeStock =
        stockBySize?.[selectedSize] ?? product.stock ?? 0;

      // Validation: quantity must be valid
      if (quantity <= 0 || quantity > selectedSizeStock) {
        toast.error('Số lượng không hợp lệ');
        return;
      }

      addToCartMutation.mutate({
        productId: product.id,
        size: selectedSize,
        quantity,
      });
    } else {
      // For products without sizes
      // Validation: quantity must be valid
      if (quantity <= 0 || quantity > product.stock) {
        toast.error('Số lượng không hợp lệ');
        return;
      }

      addToCartMutation.mutate({
        productId: product.id,
        quantity,
      });
    }
  };

  const handleBuyNow = async () => {
    if (!product || !isAuthenticated) {
      toast.error('Vui lòng đăng nhập để mua hàng');
      router.push('/auth/login');
      return;
    }

    // Check stock
    const availableStock = product.hasSizes
      ? product.sizeStocks?.find((ss) => ss.size === selectedSize)?.stock || 0
      : product.stock || 0;

    if (quantity > availableStock) {
      toast.error(
        `Số lượng vượt quá tồn kho. Tồn kho hiện tại: ${availableStock}`
      );
      return;
    }

    // For Buy Now, we need shipping address
    // For now, redirect to a checkout page with pre-filled product
    // Or we can show a modal to collect shipping address
    // For simplicity, redirect to checkout with product info in query params
    router.push(
      `/checkout?buyNow=true&productId=${product.id}&productSlug=${BACKEND_SLUG}&size=${selectedSize}&quantity=${quantity}`
    );
  };

  // Calculate stock for selected size (before early returns to maintain hook order)
  const stockBySize = product?.sizeStocks?.reduce(
    (acc, ss) => {
      acc[ss.size] = ss.stock;
      return acc;
    },
    {} as Record<ProductSize, number>
  );
  const selectedSizeStock = stockBySize?.[selectedSize] ?? product?.stock ?? 0;

  // Reset quantity when size changes if current quantity exceeds new stock
  useEffect(() => {
    if (product && product.hasSizes && quantity > selectedSizeStock) {
      setQuantity(selectedSizeStock > 0 ? selectedSizeStock : 1);
    }
  }, [selectedSize, selectedSizeStock, quantity, product]);

  const increaseQuantity = () => {
    if (product?.hasSizes) {
      setQuantity((prev) => Math.min(prev + 1, selectedSizeStock ?? 10));
    } else {
      setQuantity((prev) => Math.min(prev + 1, product?.stock ?? 10));
    }
  };

  const decreaseQuantity = () => {
    setQuantity((prev) => Math.max(prev - 1, 1));
  };

  // Map backend ProductDto to component props
  const price = {
    current: product.priceCurrent,
    original: product.priceOriginal ?? undefined,
    discount: product.priceDiscount ?? undefined,
  };

  const rating = {
    value: product.ratingValue,
    count: product.ratingCount,
  };

  const sizes = product.sizeStocks?.map((ss) => ss.size) || [];

  return (
    <>
      {/* Breadcrumb */}
      <nav className="mb-8 flex items-center gap-2 text-sm text-white/60">
        <Link href="/shop" className="hover:text-wds-accent transition-colors">
          Shop
        </Link>
        <span>/</span>
        <span className="text-white/90">{productName}</span>
      </nav>

      {/* Product Section */}
      <div className="grid grid-cols-1 gap-12 lg:grid-cols-2 lg:gap-16">
        {/* Left: Product Image */}
        <ProductImageGallery
          images={staticContent.images}
          badge={product.badge || undefined}
        />

        {/* Right: Product Info */}
        <div className="flex flex-col justify-center">
          <ProductInfo
            name={product.name}
            rating={rating}
            price={price}
            description={product.description}
            priceNote="Giá đã bao gồm VAT. Miễn phí vận chuyển cho đơn hàng trên 500.000₫"
          />

          {/* Size Selector */}
          {product.hasSizes && sizes.length > 0 && (
            <ProductSizeSelector
              sizes={sizes}
              selectedSize={selectedSize}
              onSizeChange={setSelectedSize}
              stockBySize={stockBySize}
            />
          )}

          {/* Quantity Selector */}
          <ProductQuantitySelector
            quantity={quantity}
            onIncrease={increaseQuantity}
            onDecrease={decreaseQuantity}
            stock={product.hasSizes ? selectedSizeStock : product.stock}
            max={
              product.hasSizes ? (selectedSizeStock ?? 0) : (product.stock ?? 0)
            }
          />

          {/* Add to Cart Button */}
          <ProductActions
            onAddToCart={handleAddToCart}
            onBuyNow={handleBuyNow}
            isAddingToCart={addToCartMutation.isPending}
          />

          {/* Product Features */}
          <ProductFeatures features={staticContent.features} />
        </div>
      </div>

      {/* Additional Info Section */}
      <ProductAdditionalInfo info={staticContent.additionalInfo} />

      {/* Size Guide Section - Only for products with sizes */}
      {product.hasSizes && <ProductSizeGuide />}

      {/* Reviews Section */}
      <section className="mt-16">
        <h2 className="mb-8 text-3xl font-bold text-white">
          Đánh giá sản phẩm
        </h2>

        {/* Review Form - Only for authenticated users */}
        {isAuthenticated ? (
          <div className="mb-8">
            <ReviewForm productSlug={BACKEND_SLUG} currentUserId={user?.id} />
          </div>
        ) : (
          <div className="mb-8 rounded-xl border border-white/10 bg-white/5 p-6">
            <p className="text-white/60">
              Đăng nhập để viết đánh giá về sản phẩm này.
            </p>
          </div>
        )}

        {/* Reviews List */}
        <ProductReviews
          productSlug={BACKEND_SLUG}
          currentUserId={user?.id}
          currentUserRole={user?.role}
        />
      </section>
    </>
  );
}

function ProductLoading() {
  return (
    <div className="flex flex-col gap-12">
      {/* Breadcrumb Skeleton */}
      <div className="h-5 w-48 animate-pulse rounded bg-white/10" />

      {/* Product Section Skeleton */}
      <div className="grid grid-cols-1 gap-12 lg:grid-cols-2 lg:gap-16">
        {/* Image Skeleton */}
        <div className="space-y-4">
          <div className="aspect-square w-full animate-pulse rounded-xl bg-white/10" />
          <div className="grid grid-cols-4 gap-4">
            {[1, 2, 3, 4].map((i) => (
              <div
                key={i}
                className="aspect-square animate-pulse rounded-lg bg-white/10"
              />
            ))}
          </div>
        </div>

        {/* Info Skeleton */}
        <div className="flex flex-col justify-center space-y-6">
          <div className="h-8 w-3/4 animate-pulse rounded bg-white/10" />
          <div className="h-4 w-1/2 animate-pulse rounded bg-white/10" />
          <div className="h-6 w-1/3 animate-pulse rounded bg-white/10" />
          <div className="h-20 w-full animate-pulse rounded bg-white/10" />
          <div className="h-12 w-32 animate-pulse rounded bg-white/10" />
          <div className="h-12 w-full animate-pulse rounded bg-white/10" />
          <div className="h-12 w-full animate-pulse rounded bg-white/10" />
        </div>
      </div>
    </div>
  );
}

export function ProductPageContent({
  productSlug,
  productName,
}: ProductPageContentProps) {
  return (
    <Suspense fallback={<ProductLoading />}>
      <ProductContentInner
        productSlug={productSlug}
        productName={productName}
      />
    </Suspense>
  );
}
