// apps/web/src/components/shop/ReviewItem.tsx
'use client';

import { Edit2, Star, Trash2 } from 'lucide-react';
import { useState } from 'react';

import { Button } from '@/components/ui/button';
import { useDeleteReview } from '@/lib/api/hooks/use-reviews';
import { Review } from '@/lib/api/reviews';

import { DeleteReviewDialog } from './DeleteReviewDialog';
import { ReviewEditForm } from './ReviewEditForm';

interface ReviewItemProps {
  review: Review;
  currentUserId?: string;
  currentUserRole?: string;
}

export function ReviewItem({
  review,
  currentUserId,
  currentUserRole,
}: ReviewItemProps) {
  const [isEditing, setIsEditing] = useState(false);
  const [showDeleteDialog, setShowDeleteDialog] = useState(false);
  const deleteReviewMutation = useDeleteReview();

  const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('vi-VN', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
  };

  const canEdit = currentUserId === review.userId;
  const canDelete = currentUserRole === 'ADMIN';

  const handleEditSuccess = () => {
    setIsEditing(false);
  };

  const handleDelete = () => {
    setShowDeleteDialog(true);
  };

  if (isEditing) {
    return (
      <ReviewEditForm
        review={review}
        onCancel={() => setIsEditing(false)}
        onSuccess={handleEditSuccess}
      />
    );
  }

  return (
    <>
      <div className="rounded-xl border border-white/10 bg-white/5 p-6">
        <div className="mb-4 flex items-start gap-4">
          <div className="flex h-12 w-12 items-center justify-center rounded-full bg-white/10">
            {review.userAvatar ? (
              <img
                src={review.userAvatar}
                alt={review.userFullName}
                className="h-12 w-12 rounded-full object-cover"
              />
            ) : (
              <span className="font-semibold text-white">
                {review.userFullName.charAt(0).toUpperCase()}
              </span>
            )}
          </div>
          <div className="flex-1">
            <div className="mb-2 flex items-start justify-between">
              <div>
                <p className="mb-1 font-semibold text-white">
                  {review.userFullName}
                </p>
                <div className="mb-2 flex items-center gap-2">
                  <div className="flex items-center gap-1">
                    {[1, 2, 3, 4, 5].map((i) => (
                      <Star
                        key={i}
                        className={`h-4 w-4 ${
                          i <= review.rating
                            ? 'fill-wds-accent text-wds-accent'
                            : 'text-white/20'
                        }`}
                      />
                    ))}
                  </div>
                  <span className="text-sm text-white/60">
                    {formatDate(review.createdAt)}
                  </span>
                </div>
              </div>
              {(canEdit || canDelete) && (
                <div className="flex items-center gap-2">
                  {canEdit && (
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => setIsEditing(true)}
                      className="text-white/60 hover:bg-white/10 hover:text-white"
                    >
                      <Edit2 className="h-4 w-4" />
                    </Button>
                  )}
                  {canDelete && (
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={handleDelete}
                      className="text-white/60 hover:bg-red-400/10 hover:text-red-400"
                      disabled={deleteReviewMutation.isPending}
                    >
                      <Trash2 className="h-4 w-4" />
                    </Button>
                  )}
                </div>
              )}
            </div>
            {review.comment && (
              <p className="text-white/80">{review.comment}</p>
            )}
          </div>
        </div>
      </div>

      {showDeleteDialog && (
        <DeleteReviewDialog
          reviewId={review.id}
          onClose={() => setShowDeleteDialog(false)}
          onConfirm={() => {
            deleteReviewMutation.mutate(review.id, {
              onSuccess: () => {
                setShowDeleteDialog(false);
              },
            });
          }}
          isDeleting={deleteReviewMutation.isPending}
        />
      )}
    </>
  );
}

// apps/web-vue/src/components/shop/review-item.vue
<script setup lang="ts">
import { Edit2, Star, Trash2 } from 'lucide-vue-next';
import { computed, ref } from 'vue';

import { Button } from '@/components/ui/button.vue';
import { useDeleteReview } from '@/lib/api/hooks/use-reviews';

import DeleteReviewDialog from './delete-review-dialog.vue';
import ReviewEditForm from './review-edit-form.vue';

import type { Review } from '@/lib/api/reviews';

const props = defineProps<{
  review: Review;
  currentUserId?: string;
  currentUserRole?: string;
}>();

const isEditing = ref(false);
const showDeleteDialog = ref(false);
const deleteReviewMutation = useDeleteReview();

const formatDate = (dateString: string) =>
  new Date(dateString).toLocaleDateString('vi-VN', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

const canEdit = computed(() => props.currentUserId === props.review.userId);
const canDelete = computed(() => props.currentUserRole === 'ADMIN');

const handleDeleteConfirm = () => {
  deleteReviewMutation.mutate(props.review.id, {
    onSuccess: () => {
      showDeleteDialog.value = false;
    },
  });
};
</script>

<template>
  <ReviewEditForm
    v-if="isEditing"
    :review="review"
    @cancel="isEditing = false"
    @success="isEditing = false"
  />

  <template v-else>
    <div class="rounded-xl border border-white/10 bg-white/5 p-6">
      <div class="mb-4 flex items-start gap-4">
        <div class="flex h-12 w-12 items-center justify-center rounded-full bg-white/10">
          <img
            v-if="review.userAvatar"
            :src="review.userAvatar"
            :alt="review.userFullName"
            class="h-12 w-12 rounded-full object-cover"
          />
          <span v-else class="font-semibold text-white">
            {{ review.userFullName.charAt(0).toUpperCase() }}
          </span>
        </div>
        <div class="flex-1">
          <div class="mb-2 flex items-start justify-between">
            <div>
              <p class="mb-1 font-semibold text-white">{{ review.userFullName }}</p>
              <div class="mb-2 flex items-center gap-2">
                <div class="flex items-center gap-1">
                  <Star
                    v-for="i in 5"
                    :key="i"
                    class="h-4 w-4"
                    :class="
                      i <= review.rating ? 'fill-wds-accent text-wds-accent' : 'text-white/20'
                    "
                  />
                </div>
                <span class="text-sm text-white/60">{{ formatDate(review.createdAt) }}</span>
              </div>
            </div>
            <div v-if="canEdit || canDelete" class="flex items-center gap-2">
              <Button
                v-if="canEdit"
                variant="ghost"
                size="sm"
                class="text-white/60 hover:bg-white/10 hover:text-white"
                @click="isEditing = true"
              >
                <Edit2 class="h-4 w-4" />
              </Button>
              <Button
                v-if="canDelete"
                variant="ghost"
                size="sm"
                :disabled="deleteReviewMutation.isPending.value"
                class="text-white/60 hover:bg-red-400/10 hover:text-red-400"
                @click="showDeleteDialog = true"
              >
                <Trash2 class="h-4 w-4" />
              </Button>
            </div>
          </div>
          <p v-if="review.comment" class="text-white/80">{{ review.comment }}</p>
        </div>
      </div>
    </div>

    <DeleteReviewDialog
      v-if="showDeleteDialog"
      :is-deleting="deleteReviewMutation.isPending.value"
      @close="showDeleteDialog = false"
      @confirm="handleDeleteConfirm"
    />
  </template>
</template>
