// apps/web/src/components/Navbar.tsx
'use client';

import { Menu, X } from 'lucide-react';
import { AnimatePresence, motion } from 'motion/react';
import Image from 'next/image';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useEffect, useState } from 'react';

import {
  NavigationMenu,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  navigationMenuTriggerStyle,
} from '@/components/ui/navigation-menu';
import { UserAvatar } from '@/components/wds/UserAvatar';
import { useCurrentUser } from '@/lib/api/hooks/use-auth';
import { cn } from '@/lib/utils';

interface NavbarProps {
  variant?: 'dark' | 'light';
}

export function Navbar({ variant = 'dark' }: NavbarProps) {
  const pathname = usePathname();
  const isDark = variant === 'dark';
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  const [mounted, setMounted] = useState(false);
  const { data: user } = useCurrentUser();

  useEffect(() => {
    setMounted(true);
  }, []);

  const navItems = [
    { label: 'Trang chủ', href: '/' },
    { label: 'Về chúng tôi', href: '/about' },
    { label: 'Thành tích', href: '/achievements' },
    { label: 'Hoạt động', href: '/activities' },
    { label: 'Đối tác', href: '/partner' },
    { label: 'Blog', href: '/blog' },
    { label: 'Lịch sự kiện', href: '/calendar' },
    { label: 'Thế hệ', href: '/generation' },
    { label: 'FAQ', href: '/faq' },
  ];

  return (
    <nav
      className={cn(
        'fixed top-0 right-0 left-0 z-50',
        isDark
          ? 'glass border-b border-white/5'
          : 'sticky border-b border-gray-200 bg-white'
      )}
    >
      <div className="mx-auto flex h-14 max-w-7xl items-center justify-between px-6 md:h-16">
        <Link href="/" className="group flex cursor-pointer items-center gap-2">
          <div className="relative h-6 w-6">
            <Image
              src="/image/wds-logo.svg"
              alt="WebDev Studios"
              aria-hidden="true"
              fill
              className="object-contain"
              priority
            />
          </div>
          <span
            className={cn(
              'hidden text-sm font-semibold tracking-tight lg:inline',
              isDark ? 'text-white' : 'text-black'
            )}
          >
            WebDev Studios
          </span>
        </Link>

        <NavigationMenu className="hidden md:flex">
          <NavigationMenuList className="gap-2">
            {/* Main navigation items */}
            {navItems.map((item) => {
              const isActive = pathname === item.href;
              return (
                <NavigationMenuItem key={item.href}>
                  <NavigationMenuLink
                    asChild
                    className={cn(
                      navigationMenuTriggerStyle(),
                      'h-8 text-xs font-medium',
                      isDark
                        ? isActive
                          ? 'text-wds-accent hover:bg-white/5 hover:text-white!'
                          : 'hover:text-wds-accent! text-white/70'
                        : cn(
                            'bg-transparent',
                            isActive
                              ? 'border-wds-accent rounded-none border-b-2 pb-1 text-black'
                              : 'text-gray-600 hover:text-black'
                          )
                    )}
                  >
                    <Link href={item.href}>{item.label}</Link>
                  </NavigationMenuLink>
                </NavigationMenuItem>
              );
            })}
          </NavigationMenuList>
        </NavigationMenu>

        <div className="flex items-center gap-4">
          {mounted && user ? (
            <UserAvatar variant={isDark ? 'dark' : 'light'} />
          ) : (
            <Link
              href="/auth/login"
              className={cn(
                'hidden rounded-lg px-4 py-2 text-xs font-medium transition-colors sm:block',
                isDark
                  ? 'hover:text-wds-accent text-white/70 hover:bg-white/5'
                  : 'bg-wds-accent hover:bg-wds-accent/90 text-black'
              )}
            >
              Đăng nhập
            </Link>
          )}

          {/* Mobile Menu Button */}
          <button
            onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
            className={cn(
              'flex h-10 w-10 items-center justify-center rounded-lg transition-colors md:hidden',
              isDark
                ? 'text-white/70 hover:bg-white/5 hover:text-white'
                : 'text-gray-600 hover:bg-gray-100 hover:text-black'
            )}
            aria-label="Toggle menu"
          >
            <AnimatePresence mode="wait">
              {isMobileMenuOpen ? (
                <motion.div
                  key="close"
                  initial={{ rotate: -90, opacity: 0 }}
                  animate={{ rotate: 0, opacity: 1 }}
                  exit={{ rotate: 90, opacity: 0 }}
                  transition={{ duration: 0.2 }}
                >
                  <X className="h-6 w-6" />
                </motion.div>
              ) : (
                <motion.div
                  key="menu"
                  initial={{ rotate: 90, opacity: 0 }}
                  animate={{ rotate: 0, opacity: 1 }}
                  exit={{ rotate: -90, opacity: 0 }}
                  transition={{ duration: 0.2 }}
                >
                  <Menu className="h-6 w-6" />
                </motion.div>
              )}
            </AnimatePresence>
          </button>
        </div>
      </div>

      {/* Mobile Sidebar */}
      <AnimatePresence>
        {isMobileMenuOpen && (
          <>
            {/* Backdrop */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.3 }}
              className="fixed inset-0 z-9998 bg-black/50 md:hidden"
              onClick={() => setIsMobileMenuOpen(false)}
            />

            {/* Sidebar */}
            <motion.div
              initial={{ x: '100%' }}
              animate={{ x: 0 }}
              exit={{ x: '100%' }}
              transition={{ type: 'spring', damping: 25, stiffness: 200 }}
              className={cn(
                'fixed top-0 right-0 z-9999 h-full w-80 max-w-[85vw] overflow-y-auto shadow-2xl md:hidden',
                isDark
                  ? 'glass border-l border-white/10 bg-black/98 backdrop-blur-xl'
                  : 'border-l border-gray-200 bg-white'
              )}
            >
              <div className="flex flex-col p-6">
                {/* Mobile Logo */}
                <div className="mb-8 flex items-center gap-2">
                  <div className="relative h-10 w-10">
                    <Image
                      src="/image/wds-logo.svg"
                      alt="WebDev Studios"
                      fill
                      className="object-contain"
                    />
                  </div>
                  <span
                    className={cn(
                      'text-sm font-semibold tracking-tight',
                      isDark ? 'text-white' : 'text-black'
                    )}
                  >
                    WebDev Studios
                  </span>
                </div>

                {/* Navigation Items */}
                <nav className="flex flex-col gap-2">
                  {navItems.map((item, index) => {
                    const isActive = pathname === item.href;
                    return (
                      <motion.div
                        key={item.href}
                        initial={{ opacity: 0, x: 20 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{
                          delay: index * 0.1,
                          duration: 0.3,
                          ease: [0.6, -0.05, 0.01, 0.99],
                        }}
                      >
                        <Link
                          href={item.href}
                          onClick={() => setIsMobileMenuOpen(false)}
                          className={cn(
                            'flex items-center rounded-lg px-4 py-3 text-base font-medium transition-colors',
                            isActive
                              ? isDark
                                ? 'text-wds-accent bg-white/10'
                                : 'bg-wds-accent/10 text-wds-accent'
                              : isDark
                                ? 'text-white/70 hover:bg-white/5 hover:text-white'
                                : 'text-gray-600 hover:bg-gray-100 hover:text-black'
                          )}
                        >
                          {item.label}
                        </Link>
                      </motion.div>
                    );
                  })}
                </nav>

                {/* Mobile Actions */}
                <div className="mt-8 flex flex-col gap-3">
                  {mounted && user ? (
                    <motion.div
                      initial={{ opacity: 0, x: 20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{
                        delay: navItems.length * 0.1,
                        duration: 0.3,
                      }}
                    >
                      <div className="flex justify-center">
                        <UserAvatar variant={isDark ? 'dark' : 'light'} />
                      </div>
                    </motion.div>
                  ) : (
                    <motion.div
                      initial={{ opacity: 0, x: 20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{
                        delay: navItems.length * 0.1,
                        duration: 0.3,
                      }}
                    >
                      <Link
                        href="/auth/login"
                        onClick={() => setIsMobileMenuOpen(false)}
                        className={cn(
                          'flex w-full items-center justify-center rounded-lg px-4 py-3 text-base font-medium transition-colors',
                          'bg-wds-accent hover:bg-wds-accent/90 text-black'
                        )}
                      >
                        Đăng nhập
                      </Link>
                    </motion.div>
                  )}
                </div>
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>
    </nav>
  );
}

// apps/web-vue/src/components/Navbar.vue
<script setup lang="ts">
import { Menu, X } from 'lucide-vue-next';
import { computed, onMounted, ref } from 'vue';
import { RouterLink, useRoute } from 'vue-router';

import {
  NavigationMenu,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  navigationMenuTriggerStyle,
} from '@/components/ui/navigation-menu.vue';
import UserAvatar from '@/components/wds/user-avatar.vue';
import { useCurrentUser } from '@/lib/api/hooks/use-auth';
import { cn } from 'cn';

// Port of apps/web Navbar.tsx. ponytail: motion-v open/close animations dropped for v-if —
// add <Motion> wrappers back if the sidebar transition matters.
const props = withDefaults(defineProps<{ variant?: 'dark' | 'light' }>(), { variant: 'dark' });
const route = useRoute();
const isDark = computed(() => props.variant === 'dark');
const isMobileMenuOpen = ref(false);
// mounted gate: avatar only after client render (was useSyncExternalStore in React)
const mounted = ref(false);
onMounted(() => {
  mounted.value = true;
});
const { data: user } = useCurrentUser();

const navItems = [
  { label: 'Trang chủ', href: '/' },
  { label: 'Về chúng tôi', href: '/about' },
  { label: 'Thành tích', href: '/achievements' },
  { label: 'Hoạt động', href: '/activities' },
  { label: 'Đối tác', href: '/partner' },
  { label: 'Blog', href: '/blog' },
  { label: 'Shop', href: '/shop' },
  { label: 'Lịch sự kiện', href: '/calendar' },
  { label: 'Thế hệ', href: '/generation' },
  { label: 'FAQ', href: '/faq' },
];
</script>

<template>
  <nav
    :class="
      cn(
        'fixed top-0 right-0 left-0 z-50',
        isDark ? 'glass border-b border-white/5' : 'sticky border-b border-gray-200 bg-white',
      )
    "
  >
    <div class="mx-auto flex h-14 max-w-7xl items-center justify-between px-6 md:h-16">
      <RouterLink to="/" class="group flex cursor-pointer items-center gap-2">
        <div class="relative h-6 w-6">
          <img
            src="/image/wds-logo.svg"
            alt="WebDev Studios"
            aria-hidden="true"
            class="object-contain"
          />
        </div>
        <span
          :class="
            cn(
              'hidden text-sm font-semibold tracking-tight lg:inline',
              isDark ? 'text-white' : 'text-black',
            )
          "
        >
          WebDev Studios
        </span>
      </RouterLink>

      <NavigationMenu class="hidden md:flex" :viewport="false">
        <NavigationMenuList class="gap-2">
          <!-- Main navigation items -->
          <NavigationMenuItem v-for="item in navItems" :key="item.href">
            <NavigationMenuLink
              as-child
              :class="
                cn(
                  navigationMenuTriggerStyle(),
                  'h-8 text-xs font-medium',
                  isDark
                    ? route.path === item.href
                      ? 'text-wds-accent hover:bg-white/5 hover:text-white!'
                      : 'hover:text-wds-accent! text-white/70'
                    : cn(
                        'bg-transparent',
                        route.path === item.href
                          ? 'border-wds-accent rounded-none border-b-2 pb-1 text-black'
                          : 'text-gray-600 hover:text-black',
                      ),
                )
              "
            >
              <RouterLink :to="item.href">{{ item.label }}</RouterLink>
            </NavigationMenuLink>
          </NavigationMenuItem>
        </NavigationMenuList>
      </NavigationMenu>

      <div class="flex items-center gap-4">
        <UserAvatar v-if="mounted && user" :variant="isDark ? 'dark' : 'light'" />
        <RouterLink
          v-else
          to="/auth/login"
          :class="
            cn(
              'hidden rounded-lg px-4 py-2 text-xs font-medium transition-colors sm:block',
              isDark
                ? 'hover:text-wds-accent text-white/70 hover:bg-white/5'
                : 'bg-wds-accent hover:bg-wds-accent/90 text-black',
            )
          "
        >
          Đăng nhập
        </RouterLink>

        <!-- Mobile Menu Button -->
        <button
          @click="isMobileMenuOpen = !isMobileMenuOpen"
          :class="
            cn(
              'flex h-10 w-10 items-center justify-center rounded-lg transition-colors md:hidden',
              isDark
                ? 'text-white/70 hover:bg-white/5 hover:text-white'
                : 'text-gray-600 hover:bg-gray-100 hover:text-black',
            )
          "
          aria-label="Toggle menu"
        >
          <X v-if="isMobileMenuOpen" class="h-6 w-6" />
          <Menu v-else class="h-6 w-6" />
        </button>
      </div>
    </div>

    <!-- Mobile Sidebar -->
    <template v-if="isMobileMenuOpen">
      <!-- Backdrop -->
      <div class="fixed inset-0 z-9998 bg-black/50 md:hidden" @click="isMobileMenuOpen = false" />

      <!-- Sidebar -->
      <div
        :class="
          cn(
            'fixed top-0 right-0 z-9999 h-full w-80 max-w-[85vw] overflow-y-auto shadow-2xl md:hidden',
            isDark
              ? 'glass border-l border-white/10 bg-black/98 backdrop-blur-xl'
              : 'border-l border-gray-200 bg-white',
          )
        "
      >
        <div class="flex flex-col p-6">
          <!-- Mobile Logo -->
          <div class="mb-8 flex items-center gap-2">
            <div class="relative h-10 w-10">
              <img src="/image/wds-logo.svg" alt="WebDev Studios" class="object-contain" />
            </div>
            <span
              :class="
                cn('text-sm font-semibold tracking-tight', isDark ? 'text-white' : 'text-black')
              "
            >
              WebDev Studios
            </span>
          </div>

          <!-- Navigation Items -->
          <nav class="flex flex-col gap-2">
            <RouterLink
              v-for="item in navItems"
              :key="item.href"
              :to="item.href"
              @click="isMobileMenuOpen = false"
              :class="
                cn(
                  'flex items-center rounded-lg px-4 py-3 text-base font-medium transition-colors',
                  route.path === item.href
                    ? isDark
                      ? 'text-wds-accent bg-white/10'
                      : 'bg-wds-accent/10 text-wds-accent'
                    : isDark
                      ? 'text-white/70 hover:bg-white/5 hover:text-white'
                      : 'text-gray-600 hover:bg-gray-100 hover:text-black',
                )
              "
            >
              {{ item.label }}
            </RouterLink>
          </nav>

          <!-- Mobile Actions -->
          <div class="mt-8 flex flex-col gap-3">
            <div v-if="mounted && user" class="flex justify-center">
              <UserAvatar :variant="isDark ? 'dark' : 'light'" />
            </div>
            <RouterLink
              v-else
              to="/auth/login"
              @click="isMobileMenuOpen = false"
              :class="
                cn(
                  'flex w-full items-center justify-center rounded-lg px-4 py-3 text-base font-medium transition-colors',
                  'bg-wds-accent hover:bg-wds-accent/90 text-black',
                )
              "
            >
              Đăng nhập
            </RouterLink>
          </div>
        </div>
      </div>
    </template>
  </nav>
</template>
