// apps/web/src/components/partner/PartnerHero.tsx
'use client';

import { ArrowRight } from 'lucide-react';
import { motion } from 'motion/react';
import Link from 'next/link';

export function PartnerHero() {
  return (
    <section className="mb-24 px-6">
      <div className="mx-auto max-w-4xl text-center">
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.5 }}
          className="border-wds-accent/30 bg-wds-accent/10 text-wds-accent mb-6 inline-flex items-center gap-2 rounded-full border px-4 py-1.5 text-xs font-semibold backdrop-blur-md"
        >
          <span className="relative flex h-2 w-2">
            <span className="bg-wds-accent absolute inline-flex h-full w-full animate-ping rounded-full opacity-75"></span>
            <span className="bg-wds-accent relative inline-flex h-2 w-2 rounded-full"></span>
          </span>
          Mạng lưới kết nối
        </motion.div>

        <motion.h1
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1, duration: 0.6 }}
          className="mb-6 text-4xl font-extrabold tracking-tight text-white sm:text-6xl"
        >
          Đồng hành cùng <br />
          <span className="from-wds-accent to-wds-secondary bg-linear-to-r bg-clip-text text-transparent">
            WebDev Studios
          </span>
        </motion.h1>
        <motion.p
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2, duration: 0.6 }}
          className="mx-auto mb-10 max-w-2xl text-lg text-pretty text-gray-400"
        >
          Chúng tôi tự hào được hợp tác với các doanh nghiệp công nghệ hàng đầu
          và các tổ chức uy tín để mang lại giá trị thực tiễn cho cộng đồng sinh
          viên IT.
        </motion.p>
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
          className="flex flex-col items-center justify-center gap-4 sm:flex-row"
        >
          <Link
            href="#contact"
            className="bg-wds-accent flex h-12 items-center gap-2 rounded-full px-8 font-semibold text-black transition-colors duration-200 hover:bg-white"
          >
            Trở thành đối tác <ArrowRight size={18} />
          </Link>
          <button className="h-12 rounded-full border border-white/20 px-8 text-white transition-colors duration-200 hover:bg-white/10">
            Tải hồ sơ năng lực
          </button>
        </motion.div>
      </div>
    </section>
  );
}

// apps/web-vue/src/components/partner/partner-hero.vue
<script setup lang="ts">
// Port of apps/web src/components/partner/PartnerHero.tsx.
import { ArrowRight } from 'lucide-vue-next';
import { motion } from 'motion-v';
</script>

<template>
  <section class="mb-24 px-6">
    <div class="mx-auto max-w-4xl text-center">
      <motion.div
        :initial="{ opacity: 0, scale: 0.9 }"
        :animate="{ opacity: 1, scale: 1 }"
        :transition="{ duration: 0.5 }"
        class="border-wds-accent/30 bg-wds-accent/10 text-wds-accent mb-6 inline-flex items-center gap-2 rounded-full border px-4 py-1.5 text-xs font-semibold backdrop-blur-md"
      >
        <span class="relative flex h-2 w-2">
          <span
            class="bg-wds-accent absolute inline-flex h-full w-full animate-ping rounded-full opacity-75"
          ></span>
          <span class="bg-wds-accent relative inline-flex h-2 w-2 rounded-full"></span>
        </span>
        Mạng lưới kết nối
      </motion.div>

      <motion.h1
        :initial="{ opacity: 0, y: 20 }"
        :animate="{ opacity: 1, y: 0 }"
        :transition="{ delay: 0.1, duration: 0.6 }"
        class="mb-6 text-4xl font-extrabold tracking-tight text-white sm:text-6xl"
      >
        Đồng hành cùng <br />
        <span class="from-wds-accent to-wds-secondary bg-linear-to-r bg-clip-text text-transparent">
          WebDev Studios
        </span>
      </motion.h1>
      <motion.p
        :initial="{ opacity: 0, y: 20 }"
        :animate="{ opacity: 1, y: 0 }"
        :transition="{ delay: 0.2, duration: 0.6 }"
        class="mx-auto mb-10 max-w-2xl text-lg text-pretty text-gray-400"
      >
        Chúng tôi tự hào được hợp tác với các doanh nghiệp công nghệ hàng đầu và các tổ chức uy tín
        để mang lại giá trị thực tiễn cho cộng đồng sinh viên IT.
      </motion.p>
      <motion.div
        :initial="{ opacity: 0, y: 20 }"
        :animate="{ opacity: 1, y: 0 }"
        :transition="{ delay: 0.3 }"
        class="flex flex-col items-center justify-center gap-4 sm:flex-row"
      >
        <a
          href="#contact"
          class="bg-wds-accent flex h-12 items-center gap-2 rounded-full px-8 font-semibold text-black transition-colors duration-200 hover:bg-white"
        >
          Trở thành đối tác <ArrowRight :size="18" />
        </a>
        <button
          class="h-12 rounded-full border border-white/20 px-8 text-white transition-colors duration-200 hover:bg-white/10"
        >
          Tải hồ sơ năng lực
        </button>
      </motion.div>
    </div>
  </section>
</template>
