// apps/web-vue/src/pages/auth/signup.vue
<script setup lang="ts">
import { toTypedSchema } from '@vee-validate/zod';
import { useField, useForm } from 'vee-validate';
import { z } from 'zod';

import AuthLayout from '@/components/auth/auth-layout.vue';
import Button from '@/components/ui/button.vue';
import Input from '@/components/ui/input.vue';
import { useAuth } from '@/composables/use-auth';
import { usePageMeta } from '@/lib/metadata';

usePageMeta({
  title: 'Đăng ký',
  description:
    'Tạo tài khoản WebDev Studios để truy cập các tính năng độc quyền, quản lý đơn hàng và tham gia cộng đồng.',
  path: '/auth/signup',
  image: '/seo/landing.webp',
  keywords: ['Đăng ký WDS', 'WebDev Studios signup', 'Tạo tài khoản WebDev Studios'],
});

const signupSchema = z
  .object({
    fullName: z.string().min(1, 'Vui lòng nhập họ và tên'),
    email: z.email('Email không hợp lệ').min(1, 'Email là bắt buộc'),
    password: z.string().min(1, 'Mật khẩu là bắt buộc').min(8, 'Mật khẩu phải có ít nhất 8 ký tự'),
    confirmPassword: z.string().min(1, 'Vui lòng xác nhận mật khẩu'),
    phone: z.string().optional(),
  })
  .refine((data) => data.password === data.confirmPassword, {
    message: 'Mật khẩu xác nhận không khớp',
    path: ['confirmPassword'],
  });

const { handleSubmit } = useForm({
  validationSchema: toTypedSchema(signupSchema),
  initialValues: { fullName: '', email: '', password: '', confirmPassword: '', phone: '' },
});

const {
  value: fullName,
  errorMessage: fullNameError,
  handleBlur: fullNameBlur,
} = useField<string>('fullName');
const { value: email, errorMessage: emailError, handleBlur: emailBlur } = useField<string>('email');
const {
  value: password,
  errorMessage: passwordError,
  handleBlur: passwordBlur,
} = useField<string>('password');
const {
  value: confirmPassword,
  errorMessage: confirmPasswordError,
  handleBlur: confirmPasswordBlur,
} = useField<string>('confirmPassword');
const { value: phone, errorMessage: phoneError, handleBlur: phoneBlur } = useField<string>('phone');

const auth = useAuth();
const isLoading = auth.isRegistering;

// success toast + redirect to login handled inside useRegister() hook (mirrors apps/web).
const onSubmit = handleSubmit(({ confirmPassword: _confirmPassword, ...data }) => {
  auth.register({ ...data, phone: data.phone?.trim() || undefined });
});
</script>

<template>
  <AuthLayout variant="signup">
    <div class="glass-card">
      <form class="space-y-5" @submit="onSubmit">
        <div class="space-y-2">
          <label for="fullName" class="block text-sm font-medium text-white/90">Họ và tên</label>
          <Input
            id="fullName"
            v-model="fullName"
            type="text"
            placeholder="Nhập họ và tên của bạn"
            :disabled="isLoading"
            @blur="fullNameBlur"
            class="glass-input"
          />
          <p v-if="fullNameError" class="text-sm text-red-400">
            {{ fullNameError }}
          </p>
        </div>

        <div class="space-y-2">
          <label for="email" class="block text-sm font-medium text-white/90">Email</label>
          <Input
            id="email"
            v-model="email"
            type="email"
            placeholder="Nhập địa chỉ email của bạn"
            :disabled="isLoading"
            @blur="emailBlur"
            class="glass-input"
          />
          <p v-if="emailError" class="text-sm text-red-400">{{ emailError }}</p>
        </div>

        <div class="space-y-2">
          <label for="password" class="block text-sm font-medium text-white/90">Mật khẩu</label>
          <Input
            id="password"
            v-model="password"
            type="password"
            placeholder="Tối thiểu 8 ký tự"
            :disabled="isLoading"
            @blur="passwordBlur"
            class="glass-input"
          />
          <p v-if="passwordError" class="text-sm text-red-400">
            {{ passwordError }}
          </p>
        </div>

        <div class="space-y-2">
          <label for="confirmPassword" class="block text-sm font-medium text-white/90">
            Xác nhận mật khẩu
          </label>
          <Input
            id="confirmPassword"
            v-model="confirmPassword"
            type="password"
            placeholder="Nhập lại mật khẩu"
            :disabled="isLoading"
            @blur="confirmPasswordBlur"
            class="glass-input"
          />
          <p v-if="confirmPasswordError" class="text-sm text-red-400">
            {{ confirmPasswordError }}
          </p>
        </div>

        <div class="space-y-2">
          <label for="phone" class="block text-sm font-medium text-white/90">
            Số điện thoại <span class="text-white/50">(tùy chọn)</span>
          </label>
          <Input
            id="phone"
            v-model="phone"
            type="tel"
            placeholder="Nhập số điện thoại"
            :disabled="isLoading"
            @blur="phoneBlur"
            class="glass-input"
          />
          <p v-if="phoneError" class="text-sm text-red-400">{{ phoneError }}</p>
        </div>

        <Button
          type="submit"
          :disabled="isLoading"
          class="glass-button h-12 w-full text-base font-semibold"
        >
          {{ isLoading ? 'Đang xử lý...' : 'Đăng ký' }}
        </Button>
      </form>
    </div>
  </AuthLayout>
</template>

// apps/web/src/app/auth/signup/page.tsx
'use client';

import { zodResolver } from '@hookform/resolvers/zod';
import { useForm } from 'react-hook-form';
import { z } from 'zod';

import { AuthLayout } from '@/components/auth/AuthLayout';
import { OAuthRedirectHandler } from '@/components/auth/OAuthRedirectHandler';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { useRegister } from '@/lib/api/hooks/use-auth';

// Validation schema với Zod
const signupSchema = z
  .object({
    fullName: z.string().min(1, 'Vui lòng nhập họ và tên'),
    email: z.email('Email không hợp lệ').min(1, 'Email là bắt buộc'),
    password: z
      .string()
      .min(1, 'Mật khẩu là bắt buộc')
      .min(8, 'Mật khẩu phải có ít nhất 8 ký tự'),
    confirmPassword: z.string().min(1, 'Vui lòng xác nhận mật khẩu'),
    phone: z.string().optional(),
  })
  .refine((data) => data.password === data.confirmPassword, {
    message: 'Mật khẩu xác nhận không khớp',
    path: ['confirmPassword'],
  });

type SignupFormData = z.infer<typeof signupSchema>;

export default function SignupPage() {
  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting },
  } = useForm<SignupFormData>({
    resolver: zodResolver(signupSchema),
    defaultValues: {
      phone: '',
    },
  });

  const registerMutation = useRegister();

  const onSubmit = (data: SignupFormData) => {
    // Remove confirmPassword before sending to API
    const { confirmPassword, ...registerData } = data;
    registerMutation.mutate({
      ...registerData,
      phone: registerData.phone?.trim() || undefined,
    });
  };

  const isLoading = isSubmitting || registerMutation.isPending;

  return (
    <AuthLayout variant="signup">
      <OAuthRedirectHandler />
      <div className="glass-card">
        <form onSubmit={handleSubmit(onSubmit)} className="space-y-5">
          <div className="space-y-2">
            <label
              htmlFor="fullName"
              className="block text-sm font-medium text-white/90"
            >
              Họ và tên
            </label>
            <Input
              id="fullName"
              type="text"
              placeholder="Nhập họ và tên của bạn"
              {...register('fullName')}
              disabled={isLoading}
              className="glass-input"
            />
            {errors.fullName && (
              <p className="text-sm text-red-400">{errors.fullName.message}</p>
            )}
          </div>

          <div className="space-y-2">
            <label
              htmlFor="email"
              className="block text-sm font-medium text-white/90"
            >
              Email
            </label>
            <Input
              id="email"
              type="email"
              placeholder="Nhập địa chỉ email của bạn"
              {...register('email')}
              disabled={isLoading}
              className="glass-input"
            />
            {errors.email && (
              <p className="text-sm text-red-400">{errors.email.message}</p>
            )}
          </div>

          <div className="space-y-2">
            <label
              htmlFor="password"
              className="block text-sm font-medium text-white/90"
            >
              Mật khẩu
            </label>
            <Input
              id="password"
              type="password"
              placeholder="Tối thiểu 8 ký tự"
              {...register('password')}
              disabled={isLoading}
              className="glass-input"
            />
            {errors.password && (
              <p className="text-sm text-red-400">{errors.password.message}</p>
            )}
          </div>

          <div className="space-y-2">
            <label
              htmlFor="confirmPassword"
              className="block text-sm font-medium text-white/90"
            >
              Xác nhận mật khẩu
            </label>
            <Input
              id="confirmPassword"
              type="password"
              placeholder="Nhập lại mật khẩu"
              {...register('confirmPassword')}
              disabled={isLoading}
              className="glass-input"
            />
            {errors.confirmPassword && (
              <p className="text-sm text-red-400">
                {errors.confirmPassword.message}
              </p>
            )}
          </div>

          <div className="space-y-2">
            <label
              htmlFor="phone"
              className="block text-sm font-medium text-white/90"
            >
              Số điện thoại <span className="text-white/50">(tùy chọn)</span>
            </label>
            <Input
              id="phone"
              type="tel"
              placeholder="Nhập số điện thoại"
              {...register('phone')}
              disabled={isLoading}
              className="glass-input"
            />
            {errors.phone && (
              <p className="text-sm text-red-400">{errors.phone.message}</p>
            )}
          </div>

          <Button
            type="submit"
            disabled={isLoading}
            className="glass-button h-12 w-full text-base font-semibold"
          >
            {isLoading ? 'Đang xử lý...' : 'Đăng ký'}
          </Button>
        </form>
      </div>
    </AuthLayout>
  );
}
