// apps/web/src/components/wds/AboutHero.tsx
'use client';

export function WDSAboutHero() {
  return (
    <section className="bg-white py-16">
      <div className="mx-auto max-w-7xl px-6">
        <div className="text-center">
          <h1 className="text-wds-accent mb-4 text-5xl leading-tight font-bold md:text-6xl">
            KHƠI NGUỒN - SÁNG TẠO - NẮM BẮT
          </h1>
          <p className="mb-2 text-xl font-medium text-black">
            Your idea - Your code - Your adventure
          </p>
          <p className="text-lg text-gray-700">
            Hãy khám phá một chính mình thật khác khi đồng hành cùng chúng tôi
          </p>
        </div>
      </div>
    </section>
  );
}

// apps/web-vue/src/components/wds/about-hero.vue
<script setup lang="ts">
// Port of apps/web src/components/wds/AboutHero.tsx (WDSAboutHero).
</script>

<template>
  <section class="bg-white py-16">
    <div class="mx-auto max-w-7xl px-6">
      <div class="text-center">
        <h1 class="text-wds-accent mb-4 text-5xl leading-tight font-bold md:text-6xl">
          KHƠI NGUỒN - SÁNG TẠO - NẮM BẮT
        </h1>
        <p class="mb-2 text-xl font-medium text-black">Your idea - Your code - Your adventure</p>
        <p class="text-lg text-gray-700">
          Hãy khám phá một chính mình thật khác khi đồng hành cùng chúng tôi
        </p>
      </div>
    </div>
  </section>
</template>
