// apps/web/src/components/ui/avatar.tsx
'use client';

import * as AvatarPrimitive from '@radix-ui/react-avatar';
import * as React from 'react';

import { cn } from '@/lib/utils';

export function Avatar({
  className,
  ...props
}: React.ComponentProps<typeof AvatarPrimitive.Root>) {
  return (
    <AvatarPrimitive.Root
      data-slot="avatar"
      className={cn(
        'relative flex size-8 shrink-0 overflow-hidden rounded-full',
        className
      )}
      {...props}
    />
  );
}

export function AvatarImage({
  className,
  ...props
}: React.ComponentProps<typeof AvatarPrimitive.Image>) {
  return (
    <AvatarPrimitive.Image
      data-slot="avatar-image"
      className={cn('aspect-square size-full', className)}
      {...props}
    />
  );
}

export function AvatarFallback({
  className,
  ...props
}: React.ComponentProps<typeof AvatarPrimitive.Fallback>) {
  return (
    <AvatarPrimitive.Fallback
      data-slot="avatar-fallback"
      className={cn(
        'bg-muted flex size-full items-center justify-center rounded-full',
        className
      )}
      {...props}
    />
  );
}

// apps/web-vue/src/components/ui/avatar.vue
<script lang="ts">
import {
  AvatarFallback as AvatarFallbackPrimitive,
  AvatarImage as AvatarImagePrimitive,
  AvatarRoot,
} from 'reka-ui';
import { h, type VNode } from 'vue';

import { cn } from '@/lib/cn';

function el(tag: any, base: string, slot: string) {
  return function (props: any, { attrs, slots }: any): VNode {
    return h(tag, { ...attrs, 'data-slot': slot, class: cn(base, attrs.class) }, slots.default?.());
  };
}

export const Avatar = el(
  AvatarRoot,
  'relative flex size-8 shrink-0 overflow-hidden rounded-full',
  'avatar',
);
export const AvatarImage = el(AvatarImagePrimitive, 'aspect-square size-full', 'avatar-image');
export const AvatarFallback = el(
  AvatarFallbackPrimitive,
  'bg-muted flex size-full items-center justify-center rounded-full',
  'avatar-fallback',
);

export default Avatar;
</script>
