// apps/web-vue/src/components/shop/product-quantity-selector.vue
<script setup lang="ts">
import QuantitySelector from './quantity-selector.vue';

defineProps<{
  quantity: number;
  max?: number;
  stock?: number;
}>();

defineEmits<{ increase: []; decrease: [] }>();
</script>

<template>
  <div class="mb-8">
    <label class="mb-3 block text-sm font-semibold text-white/90">Số lượng</label>
    <QuantitySelector
      :quantity="quantity"
      :max="max"
      :stock="stock"
      variant="default"
      @increase="$emit('increase')"
      @decrease="$emit('decrease')"
    />
  </div>
</template>

// apps/web/src/components/shop/ProductQuantitySelector.tsx
'use client';

import { QuantitySelector } from './QuantitySelector';

interface ProductQuantitySelectorProps {
  quantity: number;
  onIncrease: () => void;
  onDecrease: () => void;
  max?: number;
  stock?: number;
}

export function ProductQuantitySelector({
  quantity,
  onIncrease,
  onDecrease,
  max = 10,
  stock,
}: ProductQuantitySelectorProps) {
  return (
    <div className="mb-8">
      <label className="mb-3 block text-sm font-semibold text-white/90">
        Số lượng
      </label>
      <QuantitySelector
        quantity={quantity}
        onIncrease={onIncrease}
        onDecrease={onDecrease}
        max={max}
        stock={stock}
        variant="default"
        showIcons={true}
      />
    </div>
  );
}
