// apps/web-vue/src/components/shop/product-size-selector.vue
<script setup lang="ts">
import { Check } from 'lucide-vue-next';
import { Motion } from 'motion-v';

import { cn } from '@/lib/cn';

import type { ProductSize } from '@/lib/api/products';

withDefaults(
  defineProps<{
    sizes: ProductSize[];
    selectedSize: ProductSize;
    showSizeGuide?: boolean;
    stockBySize?: Partial<Record<ProductSize, number>>;
  }>(),
  { showSizeGuide: true },
);

defineEmits<{ sizeChange: [size: ProductSize] }>();
</script>

<template>
  <div class="mb-8">
    <label class="mb-3 block text-sm font-semibold text-white/90">Chọn size</label>
    <div class="flex flex-wrap gap-3">
      <button
        v-for="size in sizes"
        :key="size"
        :disabled="stockBySize?.[size] === 0"
        :class="
          cn(
            'relative flex h-12 w-16 cursor-pointer flex-col items-center justify-center rounded-xl border-2 transition-all duration-200',
            stockBySize?.[size] === 0 && 'cursor-not-allowed opacity-50',
            selectedSize === size
              ? 'border-wds-accent bg-wds-accent/10 shadow-wds-accent/20 shadow-lg'
              : 'border-white/10 bg-white/5 hover:border-white/20 hover:bg-white/10',
          )
        "
        @click="$emit('sizeChange', size)"
      >
        <span
          :class="
            cn(
              'text-sm font-semibold',
              selectedSize === size ? 'text-wds-accent' : 'text-white/70',
              stockBySize?.[size] === 0 && 'line-through',
            )
          "
        >
          {{ size }}
        </span>
        <Motion
          v-if="selectedSize === size"
          as="div"
          :initial="{ scale: 0 }"
          :animate="{ scale: 1 }"
          class="bg-wds-accent absolute -top-1 -right-1 flex h-5 w-5 items-center justify-center rounded-full"
        >
          <Check class="h-3 w-3 text-black" />
        </Motion>
        <span
          v-if="stockBySize?.[size] !== undefined && stockBySize[size]! > 0"
          class="mt-0.5 text-[10px] text-white/60"
          >{{ stockBySize[size] }}</span
        >
      </button>
    </div>
    <a
      v-if="showSizeGuide"
      href="#size-guide"
      class="text-wds-accent hover:text-wds-accent/80 mt-2 inline-block text-xs transition-colors"
      >Xem bảng size →</a
    >
  </div>
</template>

// apps/web/src/components/shop/ProductSizeSelector.tsx
'use client';

import { Check } from 'lucide-react';
import { motion } from 'motion/react';

import { ProductSize } from '@/lib/api/products';
import { cn } from '@/lib/utils';

interface ProductSizeSelectorProps {
  sizes: ProductSize[];
  selectedSize: ProductSize;
  onSizeChange: (size: ProductSize) => void;
  showSizeGuide?: boolean;
  stockBySize?: Record<ProductSize, number>;
}

export function ProductSizeSelector({
  sizes,
  selectedSize,
  onSizeChange,
  showSizeGuide = true,
  stockBySize,
}: ProductSizeSelectorProps) {
  return (
    <div className="mb-8">
      <label className="mb-3 block text-sm font-semibold text-white/90">
        Chọn size
      </label>
      <div className="flex flex-wrap gap-3">
        {sizes.map((size) => {
          const isSelected = selectedSize === size;
          const stock = stockBySize?.[size] ?? undefined;
          const isOutOfStock = stock !== undefined && stock === 0;
          return (
            <button
              key={size}
              onClick={() => !isOutOfStock && onSizeChange(size)}
              disabled={isOutOfStock}
              className={cn(
                'relative h-12 w-16 cursor-pointer rounded-xl border-2 transition-all duration-200',
                isOutOfStock && 'cursor-not-allowed opacity-50',
                isSelected
                  ? 'border-wds-accent bg-wds-accent/10 shadow-wds-accent/20 shadow-lg'
                  : 'border-white/10 bg-white/5 hover:border-white/20 hover:bg-white/10'
              )}
            >
              <span
                className={cn(
                  'text-sm font-semibold',
                  isSelected ? 'text-wds-accent' : 'text-white/70',
                  isOutOfStock && 'line-through'
                )}
              >
                {size}
              </span>
              {isSelected && (
                <motion.div
                  initial={{ scale: 0 }}
                  animate={{ scale: 1 }}
                  className="bg-wds-accent absolute -top-1 -right-1 flex h-5 w-5 items-center justify-center rounded-full"
                >
                  <Check className="h-3 w-3 text-black" />
                </motion.div>
              )}
              {stock !== undefined && stock > 0 && (
                <span className="absolute -bottom-1 left-1/2 -translate-x-1/2 text-[10px] text-white/60">
                  {stock}
                </span>
              )}
            </button>
          );
        })}
      </div>
      {showSizeGuide && (
        <a
          href="#size-guide"
          className="text-wds-accent hover:text-wds-accent/80 mt-2 inline-block text-xs transition-colors"
        >
          Xem bảng size →
        </a>
      )}
    </div>
  );
}
