// apps/web-vue/src/components/shop/quantity-selector.vue
<script setup lang="ts">
import { cva } from 'class-variance-authority';
import { Minus, Plus } from 'lucide-vue-next';
import { computed } from 'vue';

import NumberTicker from '@/components/ui/number-ticker.vue';
import { cn } from '@/lib/cn';

const quantitySelectorVariants = cva('flex items-center gap-2 rounded-lg border border-white/10', {
  variants: {
    variant: {
      default: 'bg-white/5 px-4 py-3',
      compact: 'px-1',
    },
    size: {
      sm: 'text-sm',
      md: 'text-base',
      lg: 'text-lg',
    },
  },
  defaultVariants: {
    variant: 'default',
    size: 'md',
  },
});

const quantityButtonVariants = cva(
  'cursor-pointer text-white/70 transition-colors disabled:cursor-not-allowed disabled:opacity-30 hover:text-wds-accent',
  {
    variants: {
      variant: {
        default: '',
        compact: 'h-auto px-3 py-1 hover:bg-transparent',
      },
      size: {
        sm: '',
        md: '',
        lg: '',
      },
    },
    defaultVariants: {
      variant: 'default',
      size: 'md',
    },
  },
);

const props = withDefaults(
  defineProps<{
    quantity: number;
    max?: number;
    stock?: number;
    disabled?: boolean;
    showIcons?: boolean;
    variant?: 'default' | 'compact';
    size?: 'sm' | 'md' | 'lg';
  }>(),
  { max: 10, disabled: false, showIcons: true, variant: 'default', size: 'md' },
);

defineEmits<{ increase: []; decrease: [] }>();

const maxQuantity = computed(() => (props.stock !== undefined ? props.stock : props.max));
const isDecreaseDisabled = computed(() => props.disabled || props.quantity <= 1);
const isIncreaseDisabled = computed(() => props.disabled || props.quantity >= maxQuantity.value);
</script>

<template>
  <div class="flex items-center gap-4">
    <div :class="cn(quantitySelectorVariants({ variant, size }))">
      <button
        :disabled="isDecreaseDisabled"
        :class="cn(quantityButtonVariants({ variant, size }))"
        type="button"
        aria-label="Giảm số lượng"
        @click="$emit('decrease')"
      >
        <Minus v-if="showIcons" class="h-4 w-4" />
        <span v-else class="text-base">-</span>
      </button>
      <span
        :class="
          cn('min-w-8 text-center font-semibold text-white', variant === 'compact' && 'px-4 py-1')
        "
      >
        {{ quantity }}
      </span>
      <button
        :disabled="isIncreaseDisabled"
        :class="cn(quantityButtonVariants({ variant, size }))"
        type="button"
        aria-label="Tăng số lượng"
        @click="$emit('increase')"
      >
        <Plus v-if="showIcons" class="h-4 w-4" />
        <span v-else class="text-base">+</span>
      </button>
    </div>
    <span v-if="stock !== undefined && variant === 'default'" class="text-sm text-white/60">
      Còn lại:
      <span class="font-semibold text-white">
        <NumberTicker :value="stock" :start-value="stock" class="text-white" />
      </span>
      sản phẩm
      <span v-if="quantity >= stock" class="text-wds-accent ml-2">(Đã đạt tối đa)</span>
    </span>
  </div>
</template>

// apps/web/src/components/shop/QuantitySelector.tsx
'use client';

import { cva, type VariantProps } from 'class-variance-authority';
import { Minus, Plus } from 'lucide-react';

import { NumberTicker } from '@/components/ui/number-ticker';
import { cn } from '@/lib/utils';

const quantitySelectorVariants = cva(
  'flex items-center gap-2 rounded-lg border border-white/10',
  {
    variants: {
      variant: {
        default: 'bg-white/5 px-4 py-3',
        compact: 'px-1',
      },
      size: {
        sm: 'text-sm',
        md: 'text-base',
        lg: 'text-lg',
      },
    },
    defaultVariants: {
      variant: 'default',
      size: 'md',
    },
  }
);

const quantityButtonVariants = cva(
  'cursor-pointer text-white/70 transition-colors disabled:cursor-not-allowed disabled:opacity-30 hover:text-wds-accent',
  {
    variants: {
      variant: {
        default: '',
        compact: 'h-auto px-3 py-1 hover:bg-transparent',
      },
      size: {
        sm: '',
        md: '',
        lg: '',
      },
    },
    defaultVariants: {
      variant: 'default',
      size: 'md',
    },
  }
);

interface QuantitySelectorProps extends VariantProps<
  typeof quantitySelectorVariants
> {
  quantity: number;
  onIncrease: () => void;
  onDecrease: () => void;
  max?: number;
  stock?: number;
  disabled?: boolean;
  showIcons?: boolean;
  className?: string;
}

export function QuantitySelector({
  quantity,
  onIncrease,
  onDecrease,
  max = 10,
  stock,
  disabled = false,
  showIcons = true,
  variant = 'default',
  size = 'md',
  className,
}: QuantitySelectorProps) {
  // Use stock if available, otherwise use max
  const maxQuantity = stock !== undefined ? stock : max;

  // Disable decrease if quantity is 1 or less, or if disabled
  const isDecreaseDisabled = disabled || quantity <= 1;

  // Disable increase if quantity reaches max (stock or max), or if disabled
  const isIncreaseDisabled = disabled || quantity >= maxQuantity;

  return (
    <div className={cn('flex items-center gap-4', className)}>
      <div className={cn(quantitySelectorVariants({ variant, size }))}>
        <button
          onClick={onDecrease}
          disabled={isDecreaseDisabled}
          className={cn(quantityButtonVariants({ variant, size }))}
          type="button"
          aria-label="Giảm số lượng"
        >
          {showIcons ? (
            <Minus className="h-4 w-4" />
          ) : (
            <span className="text-base">-</span>
          )}
        </button>
        <span
          className={cn(
            'min-w-8 text-center font-semibold text-white',
            variant === 'compact' && 'px-4 py-1'
          )}
        >
          {quantity}
        </span>
        <button
          onClick={onIncrease}
          disabled={isIncreaseDisabled}
          className={cn(quantityButtonVariants({ variant, size }))}
          type="button"
          aria-label="Tăng số lượng"
        >
          {showIcons ? (
            <Plus className="h-4 w-4" />
          ) : (
            <span className="text-base">+</span>
          )}
        </button>
      </div>
      {stock !== undefined && variant === 'default' && (
        <span className="text-sm text-white/60">
          Còn lại:{' '}
          <span className="font-semibold text-white">
            <NumberTicker
              value={stock}
              startValue={stock}
              className="text-white"
            />
          </span>{' '}
          sản phẩm
          {quantity >= stock && (
            <span className="text-wds-accent ml-2">(Đã đạt tối đa)</span>
          )}
        </span>
      )}
    </div>
  );
}
