// apps/web/src/components/auth/AuthLoading.tsx
import { Loader2 } from 'lucide-react';

export function AuthLoading() {
  return (
    <div className="flex min-h-[60vh] items-center justify-center">
      <div className="flex flex-col items-center gap-4">
        <Loader2 className="text-wds-accent h-8 w-8 animate-spin" />
        <p className="text-sm text-white/80">Đang tải...</p>
      </div>
    </div>
  );
}

// apps/web-vue/src/components/auth/auth-loading.vue
<script setup lang="ts"></script>

<template>
  <div class="flex min-h-[60vh] items-center justify-center">
    <div class="flex flex-col items-center gap-4">
      <div
        class="border-wds-accent h-8 w-8 animate-spin rounded-full border-2 border-t-transparent"
      />
      <p class="text-sm text-white/80">Đang tải...</p>
    </div>
  </div>
</template>
