// apps/web/src/app/admin/products/page.tsx
'use client';

import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { toast } from 'sonner';

import { AdminHeader } from '@/components/admin/AdminHeader';
import { ColumnVisibilityToggle } from '@/components/admin/ColumnVisibilityToggle';
import { DataTable } from '@/components/admin/DataTable';
import { ProductEditor } from '@/components/admin/ProductEditor';
import { TableActions } from '@/components/admin/TableActions';
import { TableFilters } from '@/components/admin/TableFilters';
import { adminApi } from '@/lib/api/admin';

const columns = [
  { id: 'id', label: 'ID' },
  { id: 'slug', label: 'Slug' },
  { id: 'name', label: 'Name' },
  { id: 'priceCurrent', label: 'Price' },
  { id: 'stock', label: 'Stock' },
  { id: 'ratingValue', label: 'Rating' },
  { id: 'isPublished', label: 'Status' },
  { id: 'actions', label: 'Actions' },
];

export default function ProductsPage() {
  const [activeTab, setActiveTab] = useState<'table' | 'editor'>('table');
  const [selectedProduct, setSelectedProduct] = useState<string | null>(null);
  const [search, setSearch] = useState('');
  const [visibleColumns, setVisibleColumns] = useState<string[]>(
    columns.map((c) => c.id)
  );

  const { data, isLoading } = useQuery({
    queryKey: ['admin', 'products'],
    queryFn: () => adminApi.listProducts(),
  });

  const filteredData =
    data?.products.filter(
      (product) =>
        product.name.toLowerCase().includes(search.toLowerCase()) ||
        product.slug.toLowerCase().includes(search.toLowerCase())
    ) || [];

  const tableData = filteredData.map((product) => ({
    ...product,
    priceCurrent: new Intl.NumberFormat('vi-VN', {
      style: 'currency',
      currency: 'VND',
    }).format(product.priceCurrent),
    isPublished: product.isPublished ? 'Published' : 'Draft',
    actions: (
      <TableActions
        onEdit={() => {
          setSelectedProduct(product.id);
          setActiveTab('editor');
        }}
      />
    ),
  }));

  return (
    <div className="flex h-full flex-col">
      <AdminHeader
        title="Products Management"
        description="Quản lý sản phẩm trong hệ thống"
      />
      <div className="flex-1 space-y-4 p-6">
        <div className="border-wds-accent/20 flex items-center gap-2 border-b">
          <button
            onClick={() => setActiveTab('table')}
            className={`cursor-pointer px-4 py-2 font-medium transition-colors ${
              activeTab === 'table'
                ? 'border-wds-accent text-wds-accent border-b-2'
                : 'text-wds-text/70 hover:text-wds-text'
            }`}
          >
            Table View
          </button>
          <button
            onClick={() => {
              if (selectedProduct) {
                setActiveTab('editor');
              } else {
                toast.info('Vui lòng chọn sản phẩm để chỉnh sửa');
              }
            }}
            className={`cursor-pointer px-4 py-2 font-medium transition-colors ${
              activeTab === 'editor'
                ? 'border-wds-accent text-wds-accent border-b-2'
                : 'text-wds-text/70 hover:text-wds-text'
            }`}
          >
            Editor
          </button>
        </div>

        {activeTab === 'table' ? (
          <>
            <div className="flex items-center justify-between">
              <TableFilters
                searchPlaceholder="Search by name or slug..."
                onSearchChange={setSearch}
                onClear={() => setSearch('')}
              />
              <ColumnVisibilityToggle
                columns={columns}
                visibleColumns={visibleColumns}
                onVisibilityChange={setVisibleColumns}
              />
            </div>
            <DataTable
              columns={columns}
              data={tableData}
              visibleColumns={visibleColumns}
              isLoading={isLoading}
              emptyMessage="No products found"
            />
          </>
        ) : (
          selectedProduct && (
            <ProductEditor
              productId={selectedProduct}
              onCancel={() => {
                setSelectedProduct(null);
                setActiveTab('table');
              }}
            />
          )
        )}
      </div>
    </div>
  );
}

// apps/web-vue/src/pages/admin/products.vue
<script setup lang="ts">
import { computed, ref } from 'vue';

import AdminHeader from '@/components/admin/admin-header.vue';
import AdminLayout from '@/components/admin/admin-layout.vue';
import ColumnVisibilityToggle from '@/components/admin/column-visibility-toggle.vue';
import DataTable from '@/components/admin/data-table.vue';
import ProductEditor from '@/components/admin/product-editor.vue';
import TableActions from '@/components/admin/table-actions.vue';
import TableFilters from '@/components/admin/table-filters.vue';
import { useAdminProducts } from '@/components/admin/use-admin';
import { toast } from '@/lib/toast';
import { usePageMeta } from '@/lib/metadata';

usePageMeta({
  title: 'Quản lý Products',
  description: 'Quản lý sản phẩm trong hệ thống WebDev Studios',
  path: '/admin/products',
});

const columns = [
  { id: 'id', label: 'ID' },
  { id: 'slug', label: 'Slug' },
  { id: 'name', label: 'Name' },
  { id: 'priceCurrent', label: 'Price' },
  { id: 'stock', label: 'Stock' },
  { id: 'ratingValue', label: 'Rating' },
  { id: 'isPublished', label: 'Status' },
  { id: 'actions', label: 'Actions' },
];

const activeTab = ref<'table' | 'editor'>('table');
const selectedProduct = ref<string | null>(null);
const search = ref('');
const visibleColumns = ref<string[]>(columns.map((c) => c.id));

const { data, isLoading } = useAdminProducts();

const filteredData = computed(
  () =>
    data.value?.products.filter(
      (product) =>
        product.name.toLowerCase().includes(search.value.toLowerCase()) ||
        product.slug.toLowerCase().includes(search.value.toLowerCase()),
    ) || [],
);

const currency = new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' });
</script>

<template>
  <AdminLayout>
    <div class="flex h-full flex-col">
      <AdminHeader title="Products Management" description="Quản lý sản phẩm trong hệ thống" />
      <div class="flex-1 space-y-4 p-6">
        <div class="border-wds-accent/20 flex items-center gap-2 border-b">
          <button
            class="cursor-pointer px-4 py-2 font-medium transition-colors"
            :class="
              activeTab === 'table'
                ? 'border-wds-accent text-wds-accent border-b-2'
                : 'text-wds-text/70 hover:text-wds-text'
            "
            @click="activeTab = 'table'"
          >
            Table View
          </button>
          <button
            class="cursor-pointer px-4 py-2 font-medium transition-colors"
            :class="
              activeTab === 'editor'
                ? 'border-wds-accent text-wds-accent border-b-2'
                : 'text-wds-text/70 hover:text-wds-text'
            "
            @click="
              if (selectedProduct) {
                activeTab = 'editor';
              } else {
                toast.info('Vui lòng chọn sản phẩm để chỉnh sửa');
              }
            "
          >
            Editor
          </button>
        </div>

        <template v-if="activeTab === 'table'">
          <div class="flex items-center justify-between">
            <TableFilters
              search-placeholder="Search by name or slug..."
              :search="search"
              @update:search="search = $event"
              :on-clear="() => (search = '')"
            />
            <ColumnVisibilityToggle v-model="visibleColumns" :columns="columns" />
          </div>
          <DataTable
            :columns="columns"
            :data="filteredData"
            :visible-columns="visibleColumns"
            :is-loading="!!isLoading"
            empty-message="No products found"
          >
            <template #cell-priceCurrent="{ row }">
              {{ currency.format(row.priceCurrent) }}
            </template>
            <template #cell-isPublished="{ row }">
              {{ row.isPublished ? 'Published' : 'Draft' }}
            </template>
            <template #cell-actions="{ row }">
              <TableActions
                :on-edit="
                  () => {
                    selectedProduct = row.id;
                    activeTab = 'editor';
                  }
                "
              />
            </template>
          </DataTable>
        </template>

        <ProductEditor
          v-else-if="selectedProduct"
          :product-id="selectedProduct"
          :on-cancel="
            () => {
              selectedProduct = null;
              activeTab = 'table';
            }
          "
        />
      </div>
    </div>
  </AdminLayout>
</template>
